name: Push image on Azure repository

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKERFILE: ./Dockerfile
  IMAGE_NAME: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/codend/frontend:latest

jobs:
  push-release-image:
    name: Push image on Azure registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}
          file: ${{ env.DOCKERFILE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
